// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxHUS9EeEtvss-1rMNWGUGPOsF2luY9qM',
    appId: '1:796358378277:web:7610f9cf923730cfc250cc',
    messagingSenderId: '796358378277',
    projectId: 'gilnyang-8a172',
    authDomain: 'gilnyang-8a172.firebaseapp.com',
    storageBucket: 'gilnyang-8a172.appspot.com',
    measurementId: 'G-SMGNJPG624',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4yQ5qCtAkC8i9hRMVZejLrj5WzLFB3lU',
    appId: '1:796358378277:android:307391ed19cad75cc250cc',
    messagingSenderId: '796358378277',
    projectId: 'gilnyang-8a172',
    storageBucket: 'gilnyang-8a172.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1cXleV5f0h0F4Fuv7r0YwpzrVXdSIGts',
    appId: '1:796358378277:ios:875c67d9addc5346c250cc',
    messagingSenderId: '796358378277',
    projectId: 'gilnyang-8a172',
    storageBucket: 'gilnyang-8a172.appspot.com',
    iosBundleId: 'com.example.roadToHanyang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1cXleV5f0h0F4Fuv7r0YwpzrVXdSIGts',
    appId: '1:796358378277:ios:875c67d9addc5346c250cc',
    messagingSenderId: '796358378277',
    projectId: 'gilnyang-8a172',
    storageBucket: 'gilnyang-8a172.appspot.com',
    iosBundleId: 'com.example.roadToHanyang',
  );
}
